name: curveauth_dart
description: ECC dart
publish_to: none
version: 1.0.0
repository: https://github.com/HayesBarber/curveauth-dart

environment:
  sdk: ^3.8.1

dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
